String.prototype.ucwords = function () {
    str = this.toLowerCase();
    return str.replace(/(^([a-zA-Z\p{M}]))|([ -][a-zA-Z\p{M}])/g,
        function (s) {
            return s.toUpperCase();
        });
};

const adjective = [
    'abandoned',
    'able',
    'absolute',
    'academic',
    'acceptable',
    'acclaimed',
    'accomplished',
    'accurate',
    'aching',
    'acidic',
    'acrobatic',
    'active',
    'actual',
    'adept',
    'admirable',
    'admired',
    'adolescent',
    'adorable',
    'adored',
    'advanced',
    'adventurous',
    'affectionate',
    'afraid',
    'aged',
    'aggravating',
    'aggressive',
    'agile',
    'agitated',
    'agonizing',
    'agreeable',
    'ajar',
    'alarmed',
    'alarming',
    'alert',
    'alienated',
    'alive',
    'all',
    'altruistic',
    'amazing',
    'ambitious',
    'ample',
    'amused',
    'amusing',
    'anchored',
    'ancient',
    'angelic',
    'angry',
    'anguished',
    'animated',
    'annual',
    'another',
    'antique',
    'anxious',
    'any',
    'apprehensive',
    'appropriate',
    'apt',
    'arctic',
    'arid',
    'aromatic',
    'artistic',
    'ashamed',
    'assured',
    'astonishing',
    'athletic',
    'attached',
    'attentive',
    'attractive',
    'austere',
    'authentic',
    'authorized',
    'automatic',
    'avaricious',
    'average',
    'aware',
    'awesome',
    'awful',
    'awkward',
]

const animal = [
    'amphibian',
    'anaconda',
    'angelfish',
    'angelshark',
    'angonoka',
    'animal',
    'anole',
    'ant',
    'anteater',
    'antelope',
    'ape',
    'aphid',
    'arachnid',
    'armadillo',
    'arthropod',
    'artiodactyls',
    'asp',
    'cassowary',
    'cat',
    'catamount',
    'caterpillar',
    'cattle',
    'cavy',
    'centipede',
    'cephalpod',
    'chameleon',
    'cheetah',
    'chickadee',
    'chicken',
    'chihuahua',
    'chimipanzee',
    'chinchilla',
    'chipmunk',
    'chiton',
    'chrysalis',
    'cicada',
]

const randomizeUsername = () => {
    const randomAnimal = animal[Math.floor(Math.random() * animal.length)];
    const randomAdjective = adjective[Math.floor(Math.random() * adjective.length)];

    const username = `${randomAdjective.ucwords()}${randomAnimal.ucwords()}`
    return username
}



module.exports = { randomizeUsername }